# Travis-CI Build for koreader
# see travis-ci.org for details

language: c

compiler:
    - gcc

env:
    - EMULATE_READER=1 USE_NO_CCACHE=1

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install libsdl1.2-dev luarocks nasm
    - git clone https://github.com/Olivine-Labs/busted/
    - cd busted && git checkout v1.10.0 && sudo luarocks make && cd ..
    - sudo luarocks install luacov
    - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev

script:
    - make fetchthirdparty all
    - sudo cp base/build/*/luajit /usr/bin/
    - make testfront

after_success:
    - make coverage
    - cd koreader-*/koreader && luacov-coveralls -v
